### ISSUE TITLE
Escrever sobre redes de colaboração

### ISSUE THREAD

**Issue by mazzoleni-gabriel** [mpgabriel95/TCC#5]
- [X] Redes de Colaboração (definição, como são formadas, exemplificar para o contexto - redes de colaboração de projetos de software)
- [x] Propriedades Topológicas/Estruturais
- [x] Propriedades Semânticas
- [x] Propriedades Temporais

**Comment by mpgabriel95** [comment]
A social network is a set of people or groups each ofwhich  has  connections  of  some  kind  to  some  or  all  of  theothers. In the language of social network analysis, the peopleor  groups  are  called  ‘‘actors’’  and  the  connections  **‘‘ties’’**

**Em dúvida da tradução correta de ties neste contexto**

**Comment by mpgabriel95** [comment]
@rebecasch Escrita primeira seção dando um contextualização sobre grafos e redes de colaboração

**Comment by mpgabriel95** [comment]
## Catalogando métricas utilizadas por cada artigo relacionado

### Batista et al. (2018) - GITSED
![image](https://user-images.githubusercontent.com/22523379/63278115-0f9a9400-c27d-11e9-9327-26f616ba51fa.png)

> Para cada uma das metricas semânticas, foram realizadas combinações com a  _tieness_ [Brandao and Moro 2017] e _resource allocation_, chamadas, respectivamente, de T e RA, conforme apresentado na Figura 2. Mais detalhes sobre as formas de calculo das métricas podem ser encontrados em [Batista et al. 2017].

Acho que vai precisar de uma seção pra explicar _tieness_ e _resource allocation_. (ou pode ficar dentro de propriedades semânticas mesmo)

### Batista et al. (2017) Aspectos temporais
 **Propriedades topológicas**
 -  Neighbothoob Overlap (NO)
 - Adamic-Adar Coefficient (AA)
 - Preferential Attachment (PA)

**Propriedades semânticas**
 - Number of shared repositories (SR)
 - Jointly developers contribution to shared repositories (JCSR)
 - Jointly developers commits to shared repositories (JCOSR)

**Propriedades semânticas com aspecto temporal**
 - Local Potential Contribution (LPC)
 - Global potential Contribution (GPC)
 - Previous Collaboration (PC)

**Comment by mpgabriel95** [comment]
**Procurar o artigo relacionado a esta apresenta;áo quando estiver na rede da udesc!!!**
https://homepages.dcc.ufmg.br/~mirella/ppt/2017-WI-Batista.pdf

**Comment by mpgabriel95** [comment]
Esse artigo explica algumas das propriedades https://homepages.dcc.ufmg.br/~mirella/pdf/2016.SBBDshort.Alves.pdf
